name: pravasitax_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Flutter configuration
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/pravasi_logo.png
    - assets/icons/home_active.svg
    - assets/icons/home_inactive.svg
    - assets/icons/feed_active.svg
    - assets/icons/feed_inactive.svg
    - assets/icons/ihub_active.svg
    - assets/icons/ihub_inactive.svg
    - assets/icons/forum_active.svg
    - assets/icons/forum_inactive.svg
    - assets/icons/chat_active.svg
    - assets/icons/chat_inactive.svg
    - assets/icons/home-hashtag.svg
    - assets/icons/percentage-square.svg
    - assets/icons/airplane.svg
    - assets/icons/receipt-2.svg

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.4.0
  file_picker: ^8.1.2
  flutter_riverpod: ^2.4.9
  http: ^1.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.12.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

# Additional configuration for your project
